# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://CGA.github.io/gdmcpy/"

git_url = "https://github.com/CGA/gdmcpy/tree/{branch}/"

def custom_doc_links(name): return None
